// Mock Bureau & KYC Gateway Service (CIBIL / Experian / NSDL / UIDAI)

export const KNOWN_BUREAU_PROFILES = [
  {
    "applicantId": "APP101",
    "name": "Rahul Sharma",
    "panNumber": "ABCPA1431F",
    "aadhaarNumber": "987654321098",
    "age": 23,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 75000,
    "existingEMI": 11250,
    "requestedLoanAmount": 600000,
    "requestedTenureMonths": 60,
    "cibilScore": 750,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 45000,
    "monthlyCredits": 75000,
    "mutualFunds": 250000,
    "savings": 80000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP102",
    "name": "Priya Patel",
    "panNumber": "BEJPL1618S",
    "aadhaarNumber": "985954191117",
    "age": 24,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 61200,
    "existingEMI": 21420,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 716,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 3,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 30600,
    "monthlyCredits": 61200,
    "mutualFunds": 525000,
    "savings": 128000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP103",
    "name": "Amit Kumar",
    "panNumber": "CHQPW1805F",
    "aadhaarNumber": "984254061136",
    "age": 25,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 46600,
    "existingEMI": 11650,
    "requestedLoanAmount": 700000,
    "requestedTenureMonths": 36,
    "cibilScore": 612,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 5,
    "dpd": 90,
    "writeOffs": 1,
    "defaults": 0,
    "bounceCount": 5,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 46600,
    "mutualFunds": 0,
    "savings": 6000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP104",
    "name": "Sneha Kulkarni",
    "panNumber": "DKXPH1992S",
    "aadhaarNumber": "982553931155",
    "age": 26,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 91000,
    "existingEMI": 16380,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 738,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 50050,
    "monthlyCredits": 91000,
    "mutualFunds": 386000,
    "savings": 108000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP105",
    "name": "Vikram Malhotra",
    "panNumber": "ENGPS2179F",
    "aadhaarNumber": "980853801174",
    "age": 27,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 55000,
    "existingEMI": 18000,
    "requestedLoanAmount": 600000,
    "requestedTenureMonths": 48,
    "cibilScore": 710,
    "scoreCategory": "Near-Prime (Excessive Bounces)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 18000,
    "monthlyCredits": 55000,
    "mutualFunds": 40000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Excessive Cheque Bounces > 2)",
    "creditSummary": "Failed banking policy check due to 3 EMI debit bounce occurrences."
  },
  {
    "applicantId": "APP106",
    "name": "Ananya Roy",
    "panNumber": "FQNPD2366S",
    "aadhaarNumber": "979153671193",
    "age": 28,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 82500,
    "existingEMI": 12375,
    "requestedLoanAmount": 1600000,
    "requestedTenureMonths": 60,
    "cibilScore": 755,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 3,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 49500,
    "monthlyCredits": 82500,
    "mutualFunds": 325000,
    "savings": 105000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP107",
    "name": "Rajesh Verma",
    "panNumber": "GTUPO2553F",
    "aadhaarNumber": "977453541212",
    "age": 29,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 67200,
    "existingEMI": 23520,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 721,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 33600,
    "monthlyCredits": 67200,
    "mutualFunds": 650000,
    "savings": 168000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP108",
    "name": "Deepak Joshi",
    "panNumber": "HWDPZ2740S",
    "aadhaarNumber": "975753411231",
    "age": 30,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 50600,
    "existingEMI": 12650,
    "requestedLoanAmount": 850000,
    "requestedTenureMonths": 36,
    "cibilScore": 617,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 4,
    "dpd": 60,
    "writeOffs": 2,
    "defaults": 0,
    "bounceCount": 4,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 50600,
    "mutualFunds": 0,
    "savings": 8500,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP109",
    "name": "Meera Nair",
    "panNumber": "IZKPK2927F",
    "aadhaarNumber": "974053281250",
    "age": 31,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 101000,
    "existingEMI": 18180,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 743,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 55550,
    "monthlyCredits": 101000,
    "mutualFunds": 446000,
    "savings": 138000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP110",
    "name": "Suresh Menon",
    "panNumber": "JDRPV3114S",
    "aadhaarNumber": "972353151269",
    "age": 32,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 24000,
    "existingEMI": 3000,
    "requestedLoanAmount": 300000,
    "requestedTenureMonths": 36,
    "cibilScore": 725,
    "scoreCategory": "Near-Prime (Low Income)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 15000,
    "monthlyCredits": 24000,
    "mutualFunds": 30000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Income < ₹30,000 Minimum Cutoff)",
    "creditSummary": "Applicant monthly salary is below institutional threshold of ₹30,000."
  },
  {
    "applicantId": "APP111",
    "name": "Aarav Gupta",
    "panNumber": "KGYPG3301F",
    "aadhaarNumber": "970653021288",
    "age": 33,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 90000,
    "existingEMI": 13500,
    "requestedLoanAmount": 1400000,
    "requestedTenureMonths": 60,
    "cibilScore": 760,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 54000,
    "monthlyCredits": 90000,
    "mutualFunds": 400000,
    "savings": 130000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP112",
    "name": "Neha Singh",
    "panNumber": "LJHPR3488S",
    "aadhaarNumber": "968952891307",
    "age": 34,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 73200,
    "existingEMI": 25620,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 726,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 4,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 36600,
    "monthlyCredits": 73200,
    "mutualFunds": 775000,
    "savings": 208000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP113",
    "name": "Rohan Chopra",
    "panNumber": "MMOPC3675F",
    "aadhaarNumber": "967252761326",
    "age": 35,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 54600,
    "existingEMI": 13650,
    "requestedLoanAmount": 400000,
    "requestedTenureMonths": 36,
    "cibilScore": 622,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 3,
    "dpd": 30,
    "writeOffs": 1,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 54600,
    "mutualFunds": 0,
    "savings": 11000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP114",
    "name": "Kavita Deshmukh",
    "panNumber": "NPVPN3862S",
    "aadhaarNumber": "965552631345",
    "age": 36,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 111000,
    "existingEMI": 19980,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 748,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 61050,
    "monthlyCredits": 111000,
    "mutualFunds": 506000,
    "savings": 168000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP115",
    "name": "Aditya Reddy",
    "panNumber": "OSEPY4049F",
    "aadhaarNumber": "963852501364",
    "age": 37,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 55000,
    "existingEMI": 18000,
    "requestedLoanAmount": 600000,
    "requestedTenureMonths": 48,
    "cibilScore": 710,
    "scoreCategory": "Near-Prime (Excessive Bounces)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 18000,
    "monthlyCredits": 55000,
    "mutualFunds": 40000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Excessive Cheque Bounces > 2)",
    "creditSummary": "Failed banking policy check due to 3 EMI debit bounce occurrences."
  },
  {
    "applicantId": "APP116",
    "name": "Pooja Agarwal",
    "panNumber": "PVLPJ4236S",
    "aadhaarNumber": "962152371383",
    "age": 38,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 97500,
    "existingEMI": 14625,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 765,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 58500,
    "monthlyCredits": 97500,
    "mutualFunds": 475000,
    "savings": 155000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP117",
    "name": "Manish Mehta",
    "panNumber": "QYSPU4423F",
    "aadhaarNumber": "960452241402",
    "age": 39,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 79200,
    "existingEMI": 27720,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 731,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 3,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 39600,
    "monthlyCredits": 79200,
    "mutualFunds": 900000,
    "savings": 248000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP118",
    "name": "Shreya Bhatia",
    "panNumber": "RCZPF4610S",
    "aadhaarNumber": "958752111421",
    "age": 40,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 58600,
    "existingEMI": 14650,
    "requestedLoanAmount": 550000,
    "requestedTenureMonths": 36,
    "cibilScore": 627,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 5,
    "dpd": 90,
    "writeOffs": 2,
    "defaults": 0,
    "bounceCount": 5,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 58600,
    "mutualFunds": 0,
    "savings": 13500,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP119",
    "name": "Siddharth Saxena",
    "panNumber": "SFIPQ4797F",
    "aadhaarNumber": "957051981440",
    "age": 41,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 121000,
    "existingEMI": 21780,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 753,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 66550,
    "monthlyCredits": 121000,
    "mutualFunds": 566000,
    "savings": 198000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP120",
    "name": "Divya Kapoor",
    "panNumber": "TIPPB4984S",
    "aadhaarNumber": "955351851459",
    "age": 42,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 24000,
    "existingEMI": 3000,
    "requestedLoanAmount": 300000,
    "requestedTenureMonths": 36,
    "cibilScore": 725,
    "scoreCategory": "Near-Prime (Low Income)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 15000,
    "monthlyCredits": 24000,
    "mutualFunds": 30000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Income < ₹30,000 Minimum Cutoff)",
    "creditSummary": "Applicant monthly salary is below institutional threshold of ₹30,000."
  },
  {
    "applicantId": "APP121",
    "name": "Gaurav Iyer",
    "panNumber": "ULWPM5171F",
    "aadhaarNumber": "953651721478",
    "age": 43,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 105000,
    "existingEMI": 15750,
    "requestedLoanAmount": 1000000,
    "requestedTenureMonths": 60,
    "cibilScore": 770,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 3,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 63000,
    "monthlyCredits": 105000,
    "mutualFunds": 550000,
    "savings": 180000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP122",
    "name": "Ritu Chatterjee",
    "panNumber": "VOFPX5358S",
    "aadhaarNumber": "951951591497",
    "age": 44,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 85200,
    "existingEMI": 29820,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 736,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 42600,
    "monthlyCredits": 85200,
    "mutualFunds": 1025000,
    "savings": 288000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP123",
    "name": "Karan Mishra",
    "panNumber": "WRMPI5545F",
    "aadhaarNumber": "950251461516",
    "age": 45,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 62600,
    "existingEMI": 15650,
    "requestedLoanAmount": 700000,
    "requestedTenureMonths": 36,
    "cibilScore": 632,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 4,
    "dpd": 60,
    "writeOffs": 1,
    "defaults": 0,
    "bounceCount": 4,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 62600,
    "mutualFunds": 0,
    "savings": 16000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP124",
    "name": "Tanvi Choudhury",
    "panNumber": "XUTPT5732S",
    "aadhaarNumber": "948551331535",
    "age": 46,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 131000,
    "existingEMI": 23580,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 758,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 72050,
    "monthlyCredits": 131000,
    "mutualFunds": 626000,
    "savings": 228000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP125",
    "name": "Varun Pandey",
    "panNumber": "YXCPE5919F",
    "aadhaarNumber": "946851201554",
    "age": 47,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 55000,
    "existingEMI": 18000,
    "requestedLoanAmount": 600000,
    "requestedTenureMonths": 48,
    "cibilScore": 710,
    "scoreCategory": "Near-Prime (Excessive Bounces)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 18000,
    "monthlyCredits": 55000,
    "mutualFunds": 40000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Excessive Cheque Bounces > 2)",
    "creditSummary": "Failed banking policy check due to 3 EMI debit bounce occurrences."
  },
  {
    "applicantId": "APP126",
    "name": "Swati Gokhale",
    "panNumber": "ZBJPP6106S",
    "aadhaarNumber": "945151071573",
    "age": 48,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 112500,
    "existingEMI": 16875,
    "requestedLoanAmount": 800000,
    "requestedTenureMonths": 60,
    "cibilScore": 775,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 67500,
    "monthlyCredits": 112500,
    "mutualFunds": 625000,
    "savings": 205000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP127",
    "name": "Nikhil Shukla",
    "panNumber": "AEQPA6293F",
    "aadhaarNumber": "943450941592",
    "age": 49,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 91200,
    "existingEMI": 31920,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 716,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 4,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 45600,
    "monthlyCredits": 91200,
    "mutualFunds": 1150000,
    "savings": 328000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP128",
    "name": "Simran Bansal",
    "panNumber": "BHXPL6480S",
    "aadhaarNumber": "941750811611",
    "age": 50,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 66600,
    "existingEMI": 16650,
    "requestedLoanAmount": 850000,
    "requestedTenureMonths": 36,
    "cibilScore": 637,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 3,
    "dpd": 30,
    "writeOffs": 2,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 66600,
    "mutualFunds": 0,
    "savings": 18500,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP129",
    "name": "Alok Tripathi",
    "panNumber": "CKGPW6667F",
    "aadhaarNumber": "940050681630",
    "age": 51,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 141000,
    "existingEMI": 25380,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 763,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 77550,
    "monthlyCredits": 141000,
    "mutualFunds": 686000,
    "savings": 258000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP130",
    "name": "Ishita Mahajan",
    "panNumber": "DNNPH6854S",
    "aadhaarNumber": "938350551649",
    "age": 52,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 24000,
    "existingEMI": 3000,
    "requestedLoanAmount": 300000,
    "requestedTenureMonths": 36,
    "cibilScore": 725,
    "scoreCategory": "Near-Prime (Low Income)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 15000,
    "monthlyCredits": 24000,
    "mutualFunds": 30000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Income < ₹30,000 Minimum Cutoff)",
    "creditSummary": "Applicant monthly salary is below institutional threshold of ₹30,000."
  },
  {
    "applicantId": "APP131",
    "name": "Harsh Pillai",
    "panNumber": "EQUPS7041F",
    "aadhaarNumber": "936650421668",
    "age": 53,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 120000,
    "existingEMI": 18000,
    "requestedLoanAmount": 600000,
    "requestedTenureMonths": 60,
    "cibilScore": 780,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 72000,
    "monthlyCredits": 120000,
    "mutualFunds": 700000,
    "savings": 230000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP132",
    "name": "Anjali Rao",
    "panNumber": "FTDPD7228S",
    "aadhaarNumber": "934950291687",
    "age": 54,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 97200,
    "existingEMI": 34020,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 721,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 3,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 48600,
    "monthlyCredits": 97200,
    "mutualFunds": 1275000,
    "savings": 368000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP133",
    "name": "Kunal Dubey",
    "panNumber": "GWKPO7415F",
    "aadhaarNumber": "933250161706",
    "age": 55,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 70600,
    "existingEMI": 17650,
    "requestedLoanAmount": 400000,
    "requestedTenureMonths": 36,
    "cibilScore": 642,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 5,
    "dpd": 90,
    "writeOffs": 1,
    "defaults": 0,
    "bounceCount": 5,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 70600,
    "mutualFunds": 0,
    "savings": 21000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP134",
    "name": "Rashmi Soni",
    "panNumber": "HZRPZ7602S",
    "aadhaarNumber": "931550031725",
    "age": 56,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 151000,
    "existingEMI": 27180,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 738,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 83050,
    "monthlyCredits": 151000,
    "mutualFunds": 746000,
    "savings": 288000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP135",
    "name": "Mayank Thakur",
    "panNumber": "IDYPK7789F",
    "aadhaarNumber": "929849901744",
    "age": 57,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 55000,
    "existingEMI": 18000,
    "requestedLoanAmount": 600000,
    "requestedTenureMonths": 48,
    "cibilScore": 710,
    "scoreCategory": "Near-Prime (Excessive Bounces)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 18000,
    "monthlyCredits": 55000,
    "mutualFunds": 40000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Excessive Cheque Bounces > 2)",
    "creditSummary": "Failed banking policy check due to 3 EMI debit bounce occurrences."
  },
  {
    "applicantId": "APP136",
    "name": "Bhavna Garg",
    "panNumber": "JGHPV7976S",
    "aadhaarNumber": "928149771763",
    "age": 58,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 127500,
    "existingEMI": 19125,
    "requestedLoanAmount": 1600000,
    "requestedTenureMonths": 60,
    "cibilScore": 785,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 3,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 76500,
    "monthlyCredits": 127500,
    "mutualFunds": 775000,
    "savings": 255000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP137",
    "name": "Pranav Chauhan",
    "panNumber": "KJOPG8163F",
    "aadhaarNumber": "926449641782",
    "age": 59,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 103200,
    "existingEMI": 36120,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 726,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 51600,
    "monthlyCredits": 103200,
    "mutualFunds": 1400000,
    "savings": 408000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP138",
    "name": "Payal Venkatesh",
    "panNumber": "LMVPR8350S",
    "aadhaarNumber": "924749511801",
    "age": 60,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 74600,
    "existingEMI": 18650,
    "requestedLoanAmount": 550000,
    "requestedTenureMonths": 36,
    "cibilScore": 647,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 4,
    "dpd": 60,
    "writeOffs": 2,
    "defaults": 0,
    "bounceCount": 4,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 74600,
    "mutualFunds": 0,
    "savings": 23500,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP139",
    "name": "Sachin Sen",
    "panNumber": "MPEPC8537F",
    "aadhaarNumber": "923049381820",
    "age": 23,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 161000,
    "existingEMI": 28980,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 743,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 88550,
    "monthlyCredits": 161000,
    "mutualFunds": 806000,
    "savings": 318000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP140",
    "name": "Deepika Grover",
    "panNumber": "NSLPN8724S",
    "aadhaarNumber": "921349251839",
    "age": 24,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 24000,
    "existingEMI": 3000,
    "requestedLoanAmount": 300000,
    "requestedTenureMonths": 36,
    "cibilScore": 725,
    "scoreCategory": "Near-Prime (Low Income)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 15000,
    "monthlyCredits": 24000,
    "mutualFunds": 30000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Income < ₹30,000 Minimum Cutoff)",
    "creditSummary": "Applicant monthly salary is below institutional threshold of ₹30,000."
  },
  {
    "applicantId": "APP141",
    "name": "Abhishek Kashyap",
    "panNumber": "OVSPY8911F",
    "aadhaarNumber": "919649121858",
    "age": 25,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 135000,
    "existingEMI": 20250,
    "requestedLoanAmount": 1400000,
    "requestedTenureMonths": 60,
    "cibilScore": 790,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 81000,
    "monthlyCredits": 135000,
    "mutualFunds": 850000,
    "savings": 280000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP142",
    "name": "Pallavi Chawla",
    "panNumber": "PYZPJ9098S",
    "aadhaarNumber": "917948991877",
    "age": 26,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 109200,
    "existingEMI": 38220,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 731,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 4,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 54600,
    "monthlyCredits": 109200,
    "mutualFunds": 1525000,
    "savings": 448000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP143",
    "name": "Vishal Sood",
    "panNumber": "QCIPU9285F",
    "aadhaarNumber": "916248861896",
    "age": 27,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 78600,
    "existingEMI": 19650,
    "requestedLoanAmount": 700000,
    "requestedTenureMonths": 36,
    "cibilScore": 652,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 3,
    "dpd": 30,
    "writeOffs": 1,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 78600,
    "mutualFunds": 0,
    "savings": 26000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP144",
    "name": "Preeti Kothari",
    "panNumber": "RFPPF9472S",
    "aadhaarNumber": "914548731915",
    "age": 28,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 171000,
    "existingEMI": 30780,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 748,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 94050,
    "monthlyCredits": 171000,
    "mutualFunds": 866000,
    "savings": 348000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP145",
    "name": "Yash Somani",
    "panNumber": "SIWPQ9659F",
    "aadhaarNumber": "912848601934",
    "age": 29,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 55000,
    "existingEMI": 18000,
    "requestedLoanAmount": 600000,
    "requestedTenureMonths": 48,
    "cibilScore": 710,
    "scoreCategory": "Near-Prime (Excessive Bounces)",
    "activeLoans": 2,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 3,
    "avgMonthlyBalance": 18000,
    "monthlyCredits": 55000,
    "mutualFunds": 40000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Excessive Cheque Bounces > 2)",
    "creditSummary": "Failed banking policy check due to 3 EMI debit bounce occurrences."
  },
  {
    "applicantId": "APP146",
    "name": "Shruti Mittal",
    "panNumber": "TLFPB9846S",
    "aadhaarNumber": "911148471953",
    "age": 30,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 142500,
    "existingEMI": 21375,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 750,
    "scoreCategory": "Super-Prime (Exceptional)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 85500,
    "monthlyCredits": 142500,
    "mutualFunds": 925000,
    "savings": 305000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Prime Score + Low FOIR)",
    "creditSummary": "Pristine repayment track record, zero past dues, healthy asset buffers."
  },
  {
    "applicantId": "APP147",
    "name": "Kartik Jain",
    "panNumber": "UOMPM1033F",
    "aadhaarNumber": "909448341972",
    "age": 31,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 115200,
    "existingEMI": 40320,
    "requestedLoanAmount": 1150000,
    "requestedTenureMonths": 60,
    "cibilScore": 736,
    "scoreCategory": "Near-Prime (Asset-Rich Exception)",
    "activeLoans": 3,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 1,
    "avgMonthlyBalance": 57600,
    "monthlyCredits": 115200,
    "mutualFunds": 1650000,
    "savings": 488000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "EXCEPTION_REQUIRED (FOIR > 50% with High Asset Buffer)",
    "creditSummary": "High debt obligations mitigated by substantial liquid mutual fund reserves."
  },
  {
    "applicantId": "APP148",
    "name": "Komal Bhattacharya",
    "panNumber": "VRTPX1220S",
    "aadhaarNumber": "907748211991",
    "age": 32,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 82600,
    "existingEMI": 20650,
    "requestedLoanAmount": 850000,
    "requestedTenureMonths": 36,
    "cibilScore": 612,
    "scoreCategory": "Sub-Prime (High Risk Knockout)",
    "activeLoans": 5,
    "dpd": 90,
    "writeOffs": 2,
    "defaults": 0,
    "bounceCount": 5,
    "avgMonthlyBalance": 12000,
    "monthlyCredits": 82600,
    "mutualFunds": 0,
    "savings": 28500,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Active Write-off / DPD Knockout)",
    "creditSummary": "Delinquency record and multiple ECS debit bounce flags trigger policy lockout."
  },
  {
    "applicantId": "APP149",
    "name": "Tushar Mukherjee",
    "panNumber": "WUCPI1407F",
    "aadhaarNumber": "906048082010",
    "age": 33,
    "employmentType": "Self-Employed",
    "declaredMonthlyIncome": 181000,
    "existingEMI": 32580,
    "requestedLoanAmount": 1200000,
    "requestedTenureMonths": 60,
    "cibilScore": 753,
    "scoreCategory": "Prime (Standard Quality)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 99550,
    "monthlyCredits": 181000,
    "mutualFunds": 926000,
    "savings": 378000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "APPROVED (Standard NBFC Policy Match)",
    "creditSummary": "Reliable corporate salary credits with manageable debt-to-income ratio."
  },
  {
    "applicantId": "APP150",
    "name": "Rupal Dutta",
    "panNumber": "XXJPT1594S",
    "aadhaarNumber": "904347952029",
    "age": 34,
    "employmentType": "Salaried",
    "declaredMonthlyIncome": 24000,
    "existingEMI": 3000,
    "requestedLoanAmount": 300000,
    "requestedTenureMonths": 36,
    "cibilScore": 725,
    "scoreCategory": "Near-Prime (Low Income)",
    "activeLoans": 1,
    "dpd": 0,
    "writeOffs": 0,
    "defaults": 0,
    "bounceCount": 0,
    "avgMonthlyBalance": 15000,
    "monthlyCredits": 24000,
    "mutualFunds": 30000,
    "savings": 15000,
    "kycStatus": "VERIFIED_NSDL_UIDAI",
    "expectedOutcome": "REJECTED (Income < ₹30,000 Minimum Cutoff)",
    "creditSummary": "Applicant monthly salary is below institutional threshold of ₹30,000."
  }
];

// Helper to normalize and validate PAN (Format: 5 letters, 4 digits, 1 letter)
export const isValidPAN = (pan) => {
  if (!pan) return false;
  const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;
  return panRegex.test(pan.trim().toUpperCase());
};

// Helper to normalize and validate Aadhaar (12 digits)
export const isValidAadhaar = (aadhaar) => {
  if (!aadhaar) return false;
  const clean = aadhaar.replace(/\s+/g, '');
  return /^[0-9]{12}$/.test(clean);
};

// Deterministic generator for custom PAN/Aadhaar entries so any user input generates consistent realistic telemetry
const generateDeterministicTelemetry = (identifier, fallbackName = 'Applicant') => {
  const cleanId = (identifier || 'CUSTOM').toUpperCase().replace(/[^A-Z0-9]/g, '');
  let hash = 0;
  for (let i = 0; i < cleanId.length; i++) {
    hash = (hash << 5) - hash + cleanId.charCodeAt(i);
    hash |= 0;
  }
  const seed = Math.abs(hash);

  // Score between 580 and 820
  const cibilScore = 580 + (seed % 241);
  const writeOffs = cibilScore < 660 ? (seed % 2) : 0;
  const bounceCount = cibilScore < 680 ? (seed % 4) + 1 : (seed % 2);
  const avgMonthlyBalance = 20000 + ((seed * 13) % 80000);
  const mutualFunds = cibilScore > 710 ? 100000 + ((seed * 17) % 600000) : ((seed * 5) % 80000);
  const savings = 25000 + ((seed * 7) % 150000);
  const activeLoans = 1 + (seed % 4);

  let scoreCategory = 'Prime';
  if (cibilScore >= 760) scoreCategory = 'Super-Prime (Exceptional)';
  else if (cibilScore >= 700) scoreCategory = 'Prime (Standard Quality)';
  else if (cibilScore >= 650) scoreCategory = 'Near-Prime (Borderline)';
  else scoreCategory = 'Sub-Prime (High Risk)';

  return {
    panNumber: isValidPAN(identifier) ? identifier.toUpperCase() : 'PAN' + cleanId.slice(0, 7),
    aadhaarNumber: isValidAadhaar(identifier) ? identifier.replace(/\s+/g, '') : 'XXXX XXXX ' + (1000 + (seed % 9000)),
    applicantId: 'APP' + (100 + (seed % 900)),
    name: fallbackName,
    age: 24 + (seed % 35),
    employmentType: seed % 3 === 0 ? 'Self-Employed' : 'Salaried',
    declaredMonthlyIncome: 45000 + ((seed * 23) % 95000),
    existingEMI: 5000 + ((seed * 11) % 25000),
    cibilScore,
    scoreCategory,
    activeLoans,
    dpd: writeOffs > 0 ? 30 : 0,
    writeOffs,
    defaults: 0,
    bounceCount,
    avgMonthlyBalance,
    monthlyCredits: 50000 + ((seed * 29) % 100000),
    mutualFunds,
    savings,
    kycStatus: 'VERIFIED_NSDL_UIDAI',
    expectedOutcome: cibilScore >= 730 && writeOffs === 0 ? 'APPROVED' : writeOffs > 0 ? 'REJECTED' : 'EXCEPTION_REQUIRED',
    creditSummary: `Auto-verified bureau profile. CIBIL score ${cibilScore}, ${activeLoans} active trade lines, ${writeOffs} write-offs recorded.`
  };
};

// Main Lookup Function
export const fetchBureauReport = async (identifier, nameHint = '') => {
  if (!identifier) {
    throw new Error('PAN Card or Aadhaar Number is required for bureau fetch');
  }

  const clean = identifier.trim().toUpperCase().replace(/\s+/g, '');

  // 1. Check known database
  const match = KNOWN_BUREAU_PROFILES.find(
    (p) => p.panNumber.toUpperCase() === clean || p.aadhaarNumber === clean
  );

  if (match) {
    return {
      ...match,
      bureauSource: 'CIBIL / Experian India Realtime Gateway',
      bureauFetchedAt: new Date().toISOString(),
      isPreConfiguredDemo: true
    };
  }

  // 2. Generate deterministic realistic profile for custom valid PAN/Aadhaar
  const generated = generateDeterministicTelemetry(clean, nameHint || 'Verified Applicant');
  return {
    ...generated,
    bureauSource: 'CIBIL / Experian India Realtime Gateway (Simulated Synthetic)',
    bureauFetchedAt: new Date().toISOString(),
    isPreConfiguredDemo: false
  };
};
